import type { RegistryEntry } from "./schema";

const peers = { react: ">=19.2", "react-native": ">=0.85 <0.87" };
const native = {
  ios: "supported" as const,
  android: "supported" as const,
  web: "experimental" as const,
};
const file = (
  name: string,
  type: "component" | "hook" | "utility" | "token" | "recipe" = "component",
) => ({
  path: `${type === "component" ? "components" : `${type}s`}/${name}.tsx`,
  type,
  target: `siren/${type === "component" ? "components" : `${type}s`}/${name}.tsx`,
});
const motionFile = {
  path: "motion.ts",
  type: "utility" as const,
  target: "siren/motion.ts",
};
const motionPressableFile = file("motion-pressable");

export const registryEntries: RegistryEntry[] = [
  {
    name: "waveform",
    version: "0.1.0-alpha.1",
    status: "experimental",
    description:
      "Bounded controlled waveform display for normalized amplitude samples.",
    files: [file("waveform")],
    registryDependencies: [],
    dependencies: ["@siren-ui/core"],
    peerDependencies: peers,
    requiresCore: "^0.1.0",
    platforms: native,
    expoGo: true,
    developmentBuildRequired: false,
    nativeConfiguration: [],
  },
  {
    name: "live-waveform",
    version: "0.1.0-alpha.1",
    status: "experimental",
    description:
      "A bounded live waveform that updates fixed native bars without React state per sample.",
    files: [
      file("live-waveform"),
      file("use-live-waveform", "hook"),
      motionFile,
    ],
    registryDependencies: [],
    dependencies: ["@siren-ui/core", "react-native-reanimated"],
    peerDependencies: { ...peers, "react-native-reanimated": ">=4.3 <4.6" },
    requiresCore: "^0.1.0",
    platforms: native,
    expoGo: true,
    developmentBuildRequired: false,
    nativeConfiguration: [
      "Install the Expo-compatible Reanimated and Worklets versions.",
    ],
  },
  {
    name: "waveform-scrubber",
    version: "0.1.0-alpha.1",
    status: "experimental",
    description: "Accessible tap and drag seeking over a normalized waveform.",
    files: [file("waveform-scrubber"), motionFile],
    registryDependencies: ["waveform"],
    dependencies: [
      "@siren-ui/core",
      "react-native-gesture-handler",
      "react-native-reanimated",
    ],
    peerDependencies: {
      ...peers,
      "react-native-gesture-handler": ">=2.28 <3",
      "react-native-reanimated": ">=4.3 <4.6",
    },
    requiresCore: "^0.1.0",
    platforms: native,
    expoGo: true,
    developmentBuildRequired: false,
    nativeConfiguration: [
      "Wrap the application root and modal roots with GestureHandlerRootView.",
    ],
  },
  {
    name: "hold-to-record",
    version: "0.1.0-alpha.2",
    status: "experimental",
    description:
      "Hold, slide-to-cancel, and slide-to-lock recording gesture primitive.",
    files: [file("hold-to-record"), motionFile],
    registryDependencies: [],
    dependencies: [
      "@siren-ui/core",
      "expo-haptics",
      "react-native-gesture-handler",
    ],
    peerDependencies: { ...peers, "react-native-gesture-handler": ">=2.28 <3" },
    requiresCore: "^0.1.0",
    platforms: native,
    expoGo: true,
    developmentBuildRequired: false,
    nativeConfiguration: [
      "Wrap the application root and modal roots with GestureHandlerRootView.",
    ],
  },
  {
    name: "recording-timer",
    version: "0.1.0-alpha.2",
    status: "experimental",
    description:
      "Accessible millisecond recording timer with warning and maximum-duration states.",
    files: [file("recording-timer")],
    registryDependencies: [],
    dependencies: ["@siren-ui/core"],
    peerDependencies: peers,
    requiresCore: "^0.1.0",
    platforms: native,
    expoGo: true,
    developmentBuildRequired: false,
    nativeConfiguration: [],
  },
  {
    name: "audio-permission-gate",
    version: "0.1.0-alpha.2",
    status: "experimental",
    description:
      "Explicit microphone permission state gate with application-owned presentation.",
    files: [
      file("audio-permission-gate"),
      file("use-audio-permission", "hook"),
    ],
    registryDependencies: [],
    dependencies: ["expo-audio"],
    peerDependencies: peers,
    platforms: native,
    expoGo: true,
    developmentBuildRequired: false,
    nativeConfiguration: [
      "Set a meaningful iOS microphone permission description through the expo-audio config plugin.",
    ],
  },
  {
    name: "audio-status-indicator",
    version: "0.1.0-beta.1",
    status: "experimental",
    description:
      "Neutral accessible presentation for meaningful audio lifecycle states.",
    files: [file("audio-status-indicator"), motionFile],
    registryDependencies: [],
    dependencies: ["react-native-reanimated"],
    peerDependencies: { ...peers, "react-native-reanimated": ">=4.3 <4.6" },
    platforms: native,
    expoGo: true,
    developmentBuildRequired: false,
    nativeConfiguration: [],
  },
  {
    name: "agent-visualizer",
    version: "0.1.0-alpha.1",
    status: "experimental",
    description:
      "Behavior-led orb, waveform-field, and radial-bars agent visualization variants.",
    files: [file("agent-visualizer"), motionFile],
    registryDependencies: [],
    dependencies: ["@siren-ui/core", "react-native-reanimated"],
    peerDependencies: { ...peers, "react-native-reanimated": ">=4.3 <4.6" },
    requiresCore: "^0.1.0",
    platforms: native,
    expoGo: true,
    developmentBuildRequired: false,
    nativeConfiguration: [
      "Install the Expo-compatible Reanimated and Worklets versions.",
    ],
  },
  {
    name: "recording-preview",
    version: "0.1.0-beta.1",
    status: "experimental",
    description:
      "Recording confirmation block with playback, scrubbing, speed, discard, and use actions.",
    files: [file("recording-preview"), motionPressableFile, motionFile],
    registryDependencies: ["voice-note-player"],
    dependencies: ["@siren-ui/core", "react-native-reanimated"],
    peerDependencies: { ...peers, "react-native-reanimated": ">=4.3 <4.6" },
    requiresCore: "^0.1.0",
    platforms: native,
    expoGo: true,
    developmentBuildRequired: false,
    nativeConfiguration: [],
  },
  {
    name: "voice-note-player",
    version: "0.1.0-beta.1",
    status: "experimental",
    description:
      "Controlled and Expo-backed voice note playback with waveform seeking and speed controls.",
    files: [
      file("voice-note-player"),
      file("use-voice-note-player", "hook"),
      motionPressableFile,
      motionFile,
    ],
    registryDependencies: ["waveform-scrubber", "audio-status-indicator"],
    dependencies: [
      "@siren-ui/core",
      "expo-asset",
      "expo-audio",
      "react-native-reanimated",
    ],
    peerDependencies: { ...peers, "react-native-reanimated": ">=4.3 <4.6" },
    requiresCore: "^0.1.0",
    platforms: native,
    expoGo: true,
    developmentBuildRequired: false,
    nativeConfiguration: [],
  },
  {
    name: "voice-note-recorder",
    version: "0.1.0-beta.1",
    status: "experimental",
    description:
      "Production-shaped composed recorder using Siren's exported primitives and Expo audio hook.",
    files: [
      file("voice-note-recorder"),
      file("use-expo-voice-recorder", "hook"),
      motionPressableFile,
      motionFile,
    ],
    registryDependencies: [
      "hold-to-record",
      "recording-timer",
      "audio-permission-gate",
      "live-waveform",
      "recording-preview",
      "audio-status-indicator",
    ],
    dependencies: ["@siren-ui/core", "expo-audio", "react-native-reanimated"],
    peerDependencies: { ...peers, "react-native-reanimated": ">=4.3 <4.6" },
    requiresCore: "^0.1.0",
    platforms: native,
    expoGo: true,
    developmentBuildRequired: true,
    nativeConfiguration: [
      "Configure expo-audio microphone permission copy and create a development build for release verification.",
    ],
  },
  {
    name: "nativewind-voice-note-recipe",
    version: "0.1.0",
    status: "experimental",
    description:
      "Optional NativeWind composition recipe without making NativeWind a registry dependency.",
    files: [file("nativewind-voice-note", "recipe")],
    registryDependencies: ["voice-note-player"],
    dependencies: ["nativewind"],
    peerDependencies: peers,
    platforms: native,
    expoGo: true,
    developmentBuildRequired: false,
    nativeConfiguration: ["Configure NativeWind in the consuming application."],
  },
];
